2024-06-18 19:37:00,536 INFO    StreamThr :7960 [internal.py:wandb_internal():89] W&B internal server running at pid: 7960, started at: 2024-06-18 19:37:00.536556
2024-06-18 19:37:00,537 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status
2024-06-18 19:37:00,545 INFO    WriterThread:7960 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\run-gi2u73pw.wandb
2024-06-18 19:37:00,546 DEBUG   SenderThread:7960 [sender.py:send():379] send: header
2024-06-18 19:37:00,589 DEBUG   SenderThread:7960 [sender.py:send():379] send: run
2024-06-18 19:37:01,361 INFO    SenderThread:7960 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files
2024-06-18 19:37:01,362 INFO    SenderThread:7960 [sender.py:_start_run_threads():1124] run started: gi2u73pw with start time 1718710620.536555
2024-06-18 19:37:01,362 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: summary_record
2024-06-18 19:37:01,362 INFO    SenderThread:7960 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 19:37:01,370 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 19:37:01,370 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: check_version
2024-06-18 19:37:01,896 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 19:37:01,921 DEBUG   HandlerThread:7960 [system_info.py:__init__():31] System info init
2024-06-18 19:37:01,922 DEBUG   HandlerThread:7960 [system_info.py:__init__():46] System info init done
2024-06-18 19:37:01,922 INFO    HandlerThread:7960 [system_monitor.py:start():181] Starting system monitor
2024-06-18 19:37:01,922 INFO    SystemMonitor:7960 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 19:37:01,922 INFO    HandlerThread:7960 [system_monitor.py:probe():201] Collecting system info
2024-06-18 19:37:01,931 INFO    SystemMonitor:7960 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 19:37:01,931 INFO    SystemMonitor:7960 [interfaces.py:start():190] Started disk monitoring
2024-06-18 19:37:01,932 INFO    SystemMonitor:7960 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 19:37:01,932 INFO    SystemMonitor:7960 [interfaces.py:start():190] Started memory monitoring
2024-06-18 19:37:01,942 INFO    SystemMonitor:7960 [interfaces.py:start():190] Started network monitoring
2024-06-18 19:37:01,942 DEBUG   HandlerThread:7960 [system_info.py:probe():195] Probing system
2024-06-18 19:37:01,944 DEBUG   HandlerThread:7960 [system_info.py:_probe_git():180] Probing git
2024-06-18 19:37:02,031 DEBUG   HandlerThread:7960 [system_info.py:_probe_git():188] Probing git done
2024-06-18 19:37:02,031 DEBUG   HandlerThread:7960 [system_info.py:probe():240] Probing system done
2024-06-18 19:37:02,031 DEBUG   HandlerThread:7960 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T11:37:01.943525', 'startedAt': '2024-06-18T11:37:00.528582', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.32388687133789}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 19:37:02,031 INFO    HandlerThread:7960 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 19:37:02,031 INFO    HandlerThread:7960 [system_monitor.py:probe():214] Publishing system info
2024-06-18 19:37:02,031 DEBUG   HandlerThread:7960 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 19:37:02,032 DEBUG   HandlerThread:7960 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 19:37:02,032 DEBUG   HandlerThread:7960 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 19:37:02,033 ERROR   HandlerThread:7960 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 19:37:02,034 DEBUG   HandlerThread:7960 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 19:37:02,035 INFO    HandlerThread:7960 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 19:37:02,038 DEBUG   SenderThread:7960 [sender.py:send():379] send: files
2024-06-18 19:37:02,038 INFO    SenderThread:7960 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 19:37:02,049 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 19:37:02,050 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: stop_status
2024-06-18 19:37:02,366 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\conda-environment.yaml
2024-06-18 19:37:02,367 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\wandb-summary.json
2024-06-18 19:37:02,367 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\requirements.txt
2024-06-18 19:37:02,367 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\wandb-metadata.json
2024-06-18 19:37:02,586 DEBUG   SenderThread:7960 [sender.py:send():379] send: telemetry
2024-06-18 19:37:02,758 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:03,171 INFO    wandb-upload_0:7960 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmpgdb1e0l4wandb\0t3mwul0-wandb-metadata.json
2024-06-18 19:37:06,390 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:06,500 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:07,775 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:08,400 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:11,520 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:12,821 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:13,541 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: partial_history
2024-06-18 19:37:13,542 DEBUG   SenderThread:7960 [sender.py:send():379] send: history
2024-06-18 19:37:13,542 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: summary_record
2024-06-18 19:37:13,543 INFO    SenderThread:7960 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 19:37:14,424 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\wandb-summary.json
2024-06-18 19:37:16,433 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:16,554 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:17,051 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 19:37:17,052 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: stop_status
2024-06-18 19:37:17,853 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:20,475 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:21,860 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:22,879 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:26,521 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:27,667 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:27,917 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:30,546 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:32,069 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 19:37:32,069 DEBUG   SenderThread:7960 [sender.py:send_request():406] send_request: stop_status
2024-06-18 19:37:32,951 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:33,655 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:33,894 ERROR   SenderThread:7960 [internal_api.py:execute():326] 409 response executing GraphQL.
2024-06-18 19:37:33,894 ERROR   SenderThread:7960 [internal_api.py:execute():327] {"errors":[{"message":"run gi2u73pw was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-18 19:37:34,573 INFO    Thread-22 :7960 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_193700-gi2u73pw\files\output.log
2024-06-18 19:37:35,313 ERROR   SenderThread:7960 [internal_api.py:execute():326] 409 response executing GraphQL.
2024-06-18 19:37:35,313 ERROR   SenderThread:7960 [internal_api.py:execute():327] {"errors":[{"message":"run gi2u73pw was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-18 19:37:37,658 ERROR   SenderThread:7960 [internal_api.py:execute():326] 409 response executing GraphQL.
2024-06-18 19:37:37,658 ERROR   SenderThread:7960 [internal_api.py:execute():327] {"errors":[{"message":"run gi2u73pw was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-18 19:37:37,659 INFO    SenderThread:7960 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 56, in execute
    request.raise_for_status()
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-06-18 19:37:38,020 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:41,982 ERROR   SenderThread:7960 [internal_api.py:execute():326] 409 response executing GraphQL.
2024-06-18 19:37:41,982 ERROR   SenderThread:7960 [internal_api.py:execute():327] {"errors":[{"message":"run gi2u73pw was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-18 19:37:43,056 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:47,092 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 19:37:48,092 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 19:37:51,114 ERROR   SenderThread:7960 [internal_api.py:execute():326] 409 response executing GraphQL.
2024-06-18 19:37:51,114 ERROR   SenderThread:7960 [internal_api.py:execute():327] {"errors":[{"message":"run gi2u73pw was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-18 19:37:52,101 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 19:37:53,102 DEBUG   HandlerThread:7960 [handler.py:handle_request():144] handle_request: status_report
