2024-06-18 11:19:09,594 INFO    StreamThr :4600 [internal.py:wandb_internal():89] W&B internal server running at pid: 4600, started at: 2024-06-18 11:19:09.593392
2024-06-18 11:19:09,595 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status
2024-06-18 11:19:09,602 INFO    WriterThread:4600 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\run-qyeo10zb.wandb
2024-06-18 11:19:09,603 DEBUG   SenderThread:4600 [sender.py:send():379] send: header
2024-06-18 11:19:09,643 DEBUG   SenderThread:4600 [sender.py:send():379] send: run
2024-06-18 11:19:10,413 INFO    SenderThread:4600 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files
2024-06-18 11:19:10,413 INFO    SenderThread:4600 [sender.py:_start_run_threads():1124] run started: qyeo10zb with start time 1718680749.594388
2024-06-18 11:19:10,413 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: summary_record
2024-06-18 11:19:10,414 INFO    SenderThread:4600 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 11:19:10,420 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 11:19:10,421 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: check_version
2024-06-18 11:19:11,422 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\wandb-summary.json
2024-06-18 11:19:14,408 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 11:19:14,425 DEBUG   HandlerThread:4600 [system_info.py:__init__():31] System info init
2024-06-18 11:19:14,425 DEBUG   HandlerThread:4600 [system_info.py:__init__():46] System info init done
2024-06-18 11:19:14,425 INFO    HandlerThread:4600 [system_monitor.py:start():181] Starting system monitor
2024-06-18 11:19:14,425 INFO    SystemMonitor:4600 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 11:19:14,426 INFO    HandlerThread:4600 [system_monitor.py:probe():201] Collecting system info
2024-06-18 11:19:14,429 INFO    SystemMonitor:4600 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 11:19:14,430 INFO    SystemMonitor:4600 [interfaces.py:start():190] Started disk monitoring
2024-06-18 11:19:14,430 INFO    SystemMonitor:4600 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 11:19:14,430 INFO    SystemMonitor:4600 [interfaces.py:start():190] Started memory monitoring
2024-06-18 11:19:14,438 INFO    SystemMonitor:4600 [interfaces.py:start():190] Started network monitoring
2024-06-18 11:19:14,450 DEBUG   HandlerThread:4600 [system_info.py:probe():195] Probing system
2024-06-18 11:19:14,451 DEBUG   HandlerThread:4600 [system_info.py:_probe_git():180] Probing git
2024-06-18 11:19:14,528 DEBUG   HandlerThread:4600 [system_info.py:_probe_git():188] Probing git done
2024-06-18 11:19:14,528 DEBUG   HandlerThread:4600 [system_info.py:probe():240] Probing system done
2024-06-18 11:19:14,528 DEBUG   HandlerThread:4600 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T03:19:14.450861', 'startedAt': '2024-06-18T03:19:09.587412', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.31573486328125}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 11:19:14,528 INFO    HandlerThread:4600 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 11:19:14,528 INFO    HandlerThread:4600 [system_monitor.py:probe():214] Publishing system info
2024-06-18 11:19:14,528 DEBUG   HandlerThread:4600 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 11:19:14,529 DEBUG   HandlerThread:4600 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 11:19:14,529 DEBUG   HandlerThread:4600 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 11:19:14,530 ERROR   HandlerThread:4600 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 11:19:14,531 DEBUG   HandlerThread:4600 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 11:19:14,531 DEBUG   HandlerThread:4600 [system_info.py:_save_code():89] Saving code
2024-06-18 11:19:14,570 DEBUG   HandlerThread:4600 [system_info.py:_save_code():110] Saving code done
2024-06-18 11:19:14,570 DEBUG   HandlerThread:4600 [system_info.py:_save_patches():127] Saving git patches
2024-06-18 11:19:15,457 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\code\system\main.py
2024-06-18 11:19:15,458 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\requirements.txt
2024-06-18 11:19:15,458 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\diff.patch
2024-06-18 11:19:15,458 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\conda-environment.yaml
2024-06-18 11:19:15,458 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\code
2024-06-18 11:19:15,458 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\code\system
2024-06-18 11:19:15,559 DEBUG   HandlerThread:4600 [system_info.py:_save_patches():169] Saving git patches done
2024-06-18 11:19:15,559 INFO    HandlerThread:4600 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 11:19:15,562 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:15,563 DEBUG   SenderThread:4600 [sender.py:send():379] send: files
2024-06-18 11:19:15,563 INFO    SenderThread:4600 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 11:19:15,563 INFO    SenderThread:4600 [sender.py:_save_file():1375] saving file code\system\main.py with policy now
2024-06-18 11:19:15,564 INFO    SenderThread:4600 [sender.py:_save_file():1375] saving file diff.patch with policy now
2024-06-18 11:19:15,579 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:19:15,579 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:19:16,244 DEBUG   SenderThread:4600 [sender.py:send():379] send: telemetry
2024-06-18 11:19:16,465 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\diff.patch
2024-06-18 11:19:16,465 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\wandb-metadata.json
2024-06-18 11:19:16,647 INFO    wandb-upload_0:4600 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmphgsb1k7xwandb\x4o8ykp5-wandb-metadata.json
2024-06-18 11:19:17,187 INFO    wandb-upload_2:4600 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmphgsb1k7xwandb\3mdbcw6u-diff.patch
2024-06-18 11:19:17,208 INFO    wandb-upload_1:4600 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmphgsb1k7xwandb\g4j3h7ie-code/system/main.py
2024-06-18 11:19:19,493 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\output.log
2024-06-18 11:19:21,086 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:21,511 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\output.log
2024-06-18 11:19:22,165 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: pause
2024-06-18 11:19:22,165 INFO    HandlerThread:4600 [handler.py:handle_request_pause():728] stopping system metrics thread or process
2024-06-18 11:19:22,165 INFO    HandlerThread:4600 [system_monitor.py:finish():190] Stopping system monitor
2024-06-18 11:19:22,165 DEBUG   SystemMonitor:4600 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-06-18 11:19:22,165 INFO    HandlerThread:4600 [interfaces.py:finish():202] Joined cpu monitor
2024-06-18 11:19:22,166 DEBUG   SystemMonitor:4600 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-06-18 11:19:22,172 INFO    HandlerThread:4600 [interfaces.py:finish():202] Joined disk monitor
2024-06-18 11:19:22,173 DEBUG   SystemMonitor:4600 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-06-18 11:19:22,224 INFO    HandlerThread:4600 [interfaces.py:finish():202] Joined gpu monitor
2024-06-18 11:19:22,224 INFO    HandlerThread:4600 [interfaces.py:finish():202] Joined memory monitor
2024-06-18 11:19:22,224 INFO    HandlerThread:4600 [interfaces.py:finish():202] Joined network monitor
2024-06-18 11:19:22,224 DEBUG   SenderThread:4600 [sender.py:send():379] send: stats
2024-06-18 11:19:26,261 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:30,574 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:19:30,574 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:19:31,828 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:36,861 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:41,907 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:42,685 INFO    Thread-16 :4600 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_111909-qyeo10zb\files\config.yaml
2024-06-18 11:19:45,586 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:19:45,587 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:19:47,925 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:52,972 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:19:58,032 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:00,597 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:20:00,598 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:20:03,905 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:08,955 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:13,993 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:15,593 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:20:15,593 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:20:19,962 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:25,009 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:30,054 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:30,609 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:20:30,609 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:20:35,917 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:40,952 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:45,613 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:20:45,613 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:20:46,895 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:51,944 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:20:56,983 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:21:00,618 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:21:00,618 DEBUG   SenderThread:4600 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:21:01,296 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:21:03,682 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:21:04,366 INFO    SenderThread:4600 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 848, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))
2024-06-18 11:21:05,663 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:08,045 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:21:10,693 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:15,732 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:17,763 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:21:20,801 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:25,854 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:30,897 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:34,603 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:21:35,931 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:40,983 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:46,009 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:51,050 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:21:56,110 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:01,171 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:06,228 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:09,434 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:22:11,281 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:16,326 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:21,378 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:26,420 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:31,474 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:36,517 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:41,565 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:46,625 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:51,667 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:22:56,698 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:01,748 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:06,793 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:11,824 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:16,880 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:21,937 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:24,323 WARNING FileStreamThread:4600 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/qyeo10zb/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A83469F448>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/qyeo10zb/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:23:27,000 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:32,059 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:37,111 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:42,165 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:47,220 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:52,284 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:23:57,325 DEBUG   HandlerThread:4600 [handler.py:handle_request():144] handle_request: keepalive
