2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Configure stats pid to 22720
2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ly\.config\wandb\settings
2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Loading settings from D:\Research-Projects-jupyter\PFLlib\system\wandb\settings
2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-06 23:20:05,560 INFO    MainThread:22720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'system\\main.py', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py'}
2024-07-06 23:20:05,561 INFO    MainThread:22720 [wandb_init.py:_log_setup():507] Logging user logs to D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240706_232005-0iktkbyr\logs\debug.log
2024-07-06 23:20:05,561 INFO    MainThread:22720 [wandb_init.py:_log_setup():508] Logging internal logs to D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240706_232005-0iktkbyr\logs\debug-internal.log
2024-07-06 23:20:05,561 INFO    MainThread:22720 [wandb_init.py:init():547] calling init triggers
2024-07-06 23:20:05,561 INFO    MainThread:22720 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {'goal': 'test', 'device': 'cuda', 'device_id': '0', 'dataset': 'Cifar10', 'num_classes': 10, 'model': FedASCLModel(
  (base): FedAvgCNN(
    (conv1): Sequential(
      (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    )
    (conv2): Sequential(
      (0): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
    )
    (fc1): Sequential(
      (0): Linear(in_features=1600, out_features=512, bias=True)
      (1): ReLU(inplace=True)
    )
    (fc): Identity()
  )
  (head): Linear(in_features=512, out_features=10, bias=True)
  (projector): Sequential(
    (0): Linear(in_features=512, out_features=512, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=512, out_features=128, bias=True)
  )
), 'batch_size': 64, 'local_learning_rate': 0.005, 'learning_rate_decay': False, 'learning_rate_decay_gamma': 0.99, 'global_rounds': 500, 'local_epochs': 1, 'algorithm': 'FedASCL', 'join_ratio': 1.0, 'random_join_ratio': False, 'num_clients': 20, 'prev': 0, 'times': 1, 'eval_gap': 10, 'save_folder_name': 'items', 'auto_break': False, 'dlg_eval': False, 'dlg_gap': 100, 'batch_num_per_client': 2, 'num_new_clients': 0, 'fine_tuning_epoch_new': 0, 'client_drop_rate': 0.0, 'train_slow_rate': 0.0, 'send_slow_rate': 0.0, 'time_select': False, 'time_threthold': 10000, 'beta': 0.0, 'lamda': 1.0, 'mu': 0.0, 'K': 5, 'p_learning_rate': 0.01, 'M': 5, 'itk': 4000, 'alphaK': 1.0, 'sigma': 1.0, 'alpha': 1.0, 'plocal_epochs': 1, 'tau': 1.0, 'fine_tuning_epochs': 10, 'dr_learning_rate': 0.0, 'L': 1.0, 'noise_dim': 512, 'generator_learning_rate': 0.005, 'hidden_dim': 512, 'server_epochs': 1000, 'localize_feature_extractor': False, 'server_learning_rate': 1.0, 'eta': 1.0, 'rand_percent': 80, 'layer_idx': 2, 'mentee_learning_rate': 0.005, 'T_start': 0.95, 'T_end': 0.98, 'momentum': 0.1, 'kl_weight': 0.0, 'wandb': 'SCL_test', 'use_wandb': True, 'margin_type': 'cNCE', 'n_views': 2, 'Alpha': 0.0, 'model_str': 'cnn', 'head': Linear(in_features=512, out_features=10, bias=True)}
2024-07-06 23:20:05,562 INFO    MainThread:22720 [wandb_init.py:init():572] re-initializing run, found existing run on stack: lsdp9imc
2024-07-06 23:20:07,585 ERROR   MainThread:22720 [wandb_init.py:init():1175] error
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_init.py", line 1147, in init
    run = wi.init()
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_init.py", line 581, in init
    latest_run.finish()
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 390, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 331, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 1885, in finish
    return self._finish(exit_code, quiet)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 1893, in _finish
    tel.feature.finish = True
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 713, in _telemetry_callback
    self._telemetry_flush()
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\wandb_run.py", line 724, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
