2024-06-18 11:43:38,840 INFO    StreamThr :10480 [internal.py:wandb_internal():89] W&B internal server running at pid: 10480, started at: 2024-06-18 11:43:38.840586
2024-06-18 11:43:38,841 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status
2024-06-18 11:43:38,850 INFO    WriterThread:10480 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\run-uzwv2sj7.wandb
2024-06-18 11:43:38,850 DEBUG   SenderThread:10480 [sender.py:send():379] send: header
2024-06-18 11:43:38,890 DEBUG   SenderThread:10480 [sender.py:send():379] send: run
2024-06-18 11:43:39,597 INFO    SenderThread:10480 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files
2024-06-18 11:43:39,598 INFO    SenderThread:10480 [sender.py:_start_run_threads():1124] run started: uzwv2sj7 with start time 1718682218.842579
2024-06-18 11:43:39,598 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: summary_record
2024-06-18 11:43:39,598 INFO    SenderThread:10480 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 11:43:39,608 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 11:43:39,608 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: check_version
2024-06-18 11:43:39,945 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 11:43:39,961 DEBUG   HandlerThread:10480 [system_info.py:__init__():31] System info init
2024-06-18 11:43:39,961 DEBUG   HandlerThread:10480 [system_info.py:__init__():46] System info init done
2024-06-18 11:43:39,961 INFO    HandlerThread:10480 [system_monitor.py:start():181] Starting system monitor
2024-06-18 11:43:39,962 INFO    SystemMonitor:10480 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 11:43:39,962 INFO    HandlerThread:10480 [system_monitor.py:probe():201] Collecting system info
2024-06-18 11:43:39,965 INFO    SystemMonitor:10480 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 11:43:39,966 INFO    SystemMonitor:10480 [interfaces.py:start():190] Started disk monitoring
2024-06-18 11:43:39,966 INFO    SystemMonitor:10480 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 11:43:39,966 INFO    SystemMonitor:10480 [interfaces.py:start():190] Started memory monitoring
2024-06-18 11:43:39,974 INFO    SystemMonitor:10480 [interfaces.py:start():190] Started network monitoring
2024-06-18 11:43:39,975 DEBUG   HandlerThread:10480 [system_info.py:probe():195] Probing system
2024-06-18 11:43:39,976 DEBUG   HandlerThread:10480 [system_info.py:_probe_git():180] Probing git
2024-06-18 11:43:40,053 DEBUG   HandlerThread:10480 [system_info.py:_probe_git():188] Probing git done
2024-06-18 11:43:40,053 DEBUG   HandlerThread:10480 [system_info.py:probe():240] Probing system done
2024-06-18 11:43:40,053 DEBUG   HandlerThread:10480 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T03:43:39.975277', 'startedAt': '2024-06-18T03:43:38.833610', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.31635284423828}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 11:43:40,053 INFO    HandlerThread:10480 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 11:43:40,053 INFO    HandlerThread:10480 [system_monitor.py:probe():214] Publishing system info
2024-06-18 11:43:40,053 DEBUG   HandlerThread:10480 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 11:43:40,053 DEBUG   HandlerThread:10480 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 11:43:40,054 DEBUG   HandlerThread:10480 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 11:43:40,055 ERROR   HandlerThread:10480 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 11:43:40,055 DEBUG   HandlerThread:10480 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 11:43:40,055 DEBUG   HandlerThread:10480 [system_info.py:_save_code():89] Saving code
2024-06-18 11:43:40,093 DEBUG   HandlerThread:10480 [system_info.py:_save_code():110] Saving code done
2024-06-18 11:43:40,093 DEBUG   HandlerThread:10480 [system_info.py:_save_patches():127] Saving git patches
2024-06-18 11:43:40,609 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\conda-environment.yaml
2024-06-18 11:43:40,609 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\requirements.txt
2024-06-18 11:43:40,609 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\wandb-summary.json
2024-06-18 11:43:40,610 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\code\system\main.py
2024-06-18 11:43:40,610 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\code
2024-06-18 11:43:40,610 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\code\system
2024-06-18 11:43:41,078 DEBUG   HandlerThread:10480 [system_info.py:_save_patches():169] Saving git patches done
2024-06-18 11:43:41,079 INFO    HandlerThread:10480 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 11:43:41,082 DEBUG   SenderThread:10480 [sender.py:send():379] send: files
2024-06-18 11:43:41,082 INFO    SenderThread:10480 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 11:43:41,082 INFO    SenderThread:10480 [sender.py:_save_file():1375] saving file code\system\main.py with policy now
2024-06-18 11:43:41,083 INFO    SenderThread:10480 [sender.py:_save_file():1375] saving file diff.patch with policy now
2024-06-18 11:43:41,096 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:43:41,096 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:43:41,620 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\wandb-metadata.json
2024-06-18 11:43:41,620 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\diff.patch
2024-06-18 11:43:41,655 DEBUG   SenderThread:10480 [sender.py:send():379] send: telemetry
2024-06-18 11:43:42,241 INFO    wandb-upload_0:10480 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp5t87di25wandb\nydqg31m-wandb-metadata.json
2024-06-18 11:43:42,596 INFO    wandb-upload_2:10480 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp5t87di25wandb\0puej0ur-diff.patch
2024-06-18 11:43:42,690 INFO    wandb-upload_1:10480 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp5t87di25wandb\o9wsajht-code/system/main.py
2024-06-18 11:43:44,518 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:43:44,643 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\output.log
2024-06-18 11:43:46,655 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\output.log
2024-06-18 11:43:49,538 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:43:54,583 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:43:56,098 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:43:56,099 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:44:00,376 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:05,427 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:10,469 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:11,098 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:44:11,098 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:44:11,825 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\config.yaml
2024-06-18 11:44:16,465 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:21,511 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:26,106 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:44:26,107 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:44:27,401 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:28,183 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: partial_history
2024-06-18 11:44:28,184 DEBUG   SenderThread:10480 [sender.py:send():379] send: history
2024-06-18 11:44:28,184 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: summary_record
2024-06-18 11:44:28,185 INFO    SenderThread:10480 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 11:44:28,338 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: pause
2024-06-18 11:44:28,338 INFO    HandlerThread:10480 [handler.py:handle_request_pause():728] stopping system metrics thread or process
2024-06-18 11:44:28,338 INFO    HandlerThread:10480 [system_monitor.py:finish():190] Stopping system monitor
2024-06-18 11:44:28,338 DEBUG   SystemMonitor:10480 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-06-18 11:44:28,338 DEBUG   SystemMonitor:10480 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-06-18 11:44:28,339 INFO    HandlerThread:10480 [interfaces.py:finish():202] Joined cpu monitor
2024-06-18 11:44:28,339 DEBUG   SystemMonitor:10480 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-06-18 11:44:28,345 INFO    HandlerThread:10480 [interfaces.py:finish():202] Joined disk monitor
2024-06-18 11:44:28,395 INFO    HandlerThread:10480 [interfaces.py:finish():202] Joined gpu monitor
2024-06-18 11:44:28,395 INFO    HandlerThread:10480 [interfaces.py:finish():202] Joined memory monitor
2024-06-18 11:44:28,395 INFO    HandlerThread:10480 [interfaces.py:finish():202] Joined network monitor
2024-06-18 11:44:28,396 DEBUG   SenderThread:10480 [sender.py:send():379] send: stats
2024-06-18 11:44:29,000 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\output.log
2024-06-18 11:44:29,001 INFO    Thread-16 :10480 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_114338-uzwv2sj7\files\wandb-summary.json
2024-06-18 11:44:32,434 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:37,476 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:44:41,115 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:44:41,115 DEBUG   SenderThread:10480 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:44:46,151 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:44:51,203 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:44:56,238 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:01,297 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:06,334 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:11,378 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:14,392 INFO    SenderThread:10480 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connection.py", line 202, in _new_conn
    socket_options=self.socket_options,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 805, in urlopen
    **response_kw,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    ) from e
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001A178B15F48>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 848, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A178B15F48>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A178B15F48>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2024-06-18 11:45:16,420 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:21,471 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:26,523 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:28,273 WARNING FileStreamThread:10480 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A178A2F348>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/uzwv2sj7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:45:31,575 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:36,612 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:41,646 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:46,687 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:45:51,442 WARNING FileStreamThread:10480 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/uzwv2sj7/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A178CD6788>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001A178A2F348>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/uzwv2sj7/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:45:51,724 DEBUG   HandlerThread:10480 [handler.py:handle_request():144] handle_request: keepalive
