2024-06-18 11:02:37,433 INFO    StreamThr :20712 [internal.py:wandb_internal():89] W&B internal server running at pid: 20712, started at: 2024-06-18 11:02:37.433151
2024-06-18 11:02:37,434 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status
2024-06-18 11:02:37,443 INFO    WriterThread:20712 [datastore.py:open_for_write():85] open: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\run-mq1q3hm3.wandb
2024-06-18 11:02:37,444 DEBUG   SenderThread:20712 [sender.py:send():379] send: header
2024-06-18 11:02:37,493 DEBUG   SenderThread:20712 [sender.py:send():379] send: run
2024-06-18 11:02:38,309 INFO    SenderThread:20712 [dir_watcher.py:__init__():211] watching files in: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files
2024-06-18 11:02:38,309 INFO    SenderThread:20712 [sender.py:_start_run_threads():1124] run started: mq1q3hm3 with start time 1718679757.434147
2024-06-18 11:02:38,309 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: summary_record
2024-06-18 11:02:38,309 INFO    SenderThread:20712 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2024-06-18 11:02:38,317 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: check_version
2024-06-18 11:02:38,317 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: check_version
2024-06-18 11:02:38,665 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: run_start
2024-06-18 11:02:38,682 DEBUG   HandlerThread:20712 [system_info.py:__init__():31] System info init
2024-06-18 11:02:38,682 DEBUG   HandlerThread:20712 [system_info.py:__init__():46] System info init done
2024-06-18 11:02:38,682 INFO    HandlerThread:20712 [system_monitor.py:start():181] Starting system monitor
2024-06-18 11:02:38,683 INFO    SystemMonitor:20712 [system_monitor.py:_start():145] Starting system asset monitoring threads
2024-06-18 11:02:38,683 INFO    HandlerThread:20712 [system_monitor.py:probe():201] Collecting system info
2024-06-18 11:02:38,687 INFO    SystemMonitor:20712 [interfaces.py:start():190] Started cpu monitoring
2024-06-18 11:02:38,687 INFO    SystemMonitor:20712 [interfaces.py:start():190] Started disk monitoring
2024-06-18 11:02:38,688 INFO    SystemMonitor:20712 [interfaces.py:start():190] Started gpu monitoring
2024-06-18 11:02:38,688 INFO    SystemMonitor:20712 [interfaces.py:start():190] Started memory monitoring
2024-06-18 11:02:38,695 INFO    SystemMonitor:20712 [interfaces.py:start():190] Started network monitoring
2024-06-18 11:02:38,703 DEBUG   HandlerThread:20712 [system_info.py:probe():195] Probing system
2024-06-18 11:02:38,704 DEBUG   HandlerThread:20712 [system_info.py:_probe_git():180] Probing git
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_info.py:_probe_git():188] Probing git done
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_info.py:probe():240] Probing system done
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.19041-SP0', 'python': '3.7.12', 'heartbeatAt': '2024-06-18T03:02:38.703250', 'startedAt': '2024-06-18T03:02:37.423186', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Research-Projects-jupyter\\PFLlib\\system\\main.py', 'codePath': 'system\\main.py', 'git': {'remote': 'https://github.com/TsingZ0/PFLlib.git', 'commit': '004a405da7c159e843d98b2a53e2114d4f859912'}, 'email': '1731485214@qq.com', 'root': 'D:/Research-Projects-jupyter/PFLlib', 'host': 'DESKTOP-4LOGPS7', 'username': 'paddeyzhang', 'executable': 'D:\\Reseach Software\\envs\\fl\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2500.0, 'min': 0.0, 'max': 2500.0}, 'cpu_freq_per_core': [{'current': 2500.0, 'min': 0.0, 'max': 2500.0}], 'disk': {'total': 199.99901962280273, 'used': 69.31546020507812}, 'gpu': 'NVIDIA GeForce RTX 3070', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070', 'memory_total': 8589934592}], 'memory': {'total': 15.842487335205078}}
2024-06-18 11:02:38,780 INFO    HandlerThread:20712 [system_monitor.py:probe():211] Finished collecting system info
2024-06-18 11:02:38,780 INFO    HandlerThread:20712 [system_monitor.py:probe():214] Publishing system info
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_info.py:_save_pip():67] Saving pip packages done
2024-06-18 11:02:38,780 DEBUG   HandlerThread:20712 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-06-18 11:02:38,781 ERROR   HandlerThread:20712 [system_info.py:_save_conda():85] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 82, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Reseach Software\envs\fl\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-06-18 11:02:38,783 DEBUG   HandlerThread:20712 [system_info.py:_save_conda():86] Saving conda packages done
2024-06-18 11:02:38,783 DEBUG   HandlerThread:20712 [system_info.py:_save_code():89] Saving code
2024-06-18 11:02:38,822 DEBUG   HandlerThread:20712 [system_info.py:_save_code():110] Saving code done
2024-06-18 11:02:38,822 DEBUG   HandlerThread:20712 [system_info.py:_save_patches():127] Saving git patches
2024-06-18 11:02:39,313 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\code\system\main.py
2024-06-18 11:02:39,313 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\conda-environment.yaml
2024-06-18 11:02:39,314 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\wandb-summary.json
2024-06-18 11:02:39,314 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\requirements.txt
2024-06-18 11:02:39,314 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\code\system
2024-06-18 11:02:39,314 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\code
2024-06-18 11:02:39,881 DEBUG   HandlerThread:20712 [system_info.py:_save_patches():169] Saving git patches done
2024-06-18 11:02:39,882 INFO    HandlerThread:20712 [system_monitor.py:probe():216] Finished publishing system info
2024-06-18 11:02:39,885 DEBUG   SenderThread:20712 [sender.py:send():379] send: files
2024-06-18 11:02:39,885 INFO    SenderThread:20712 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2024-06-18 11:02:39,885 INFO    SenderThread:20712 [sender.py:_save_file():1375] saving file code\system\main.py with policy now
2024-06-18 11:02:39,886 INFO    SenderThread:20712 [sender.py:_save_file():1375] saving file diff.patch with policy now
2024-06-18 11:02:39,903 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:02:39,903 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:02:40,326 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\diff.patch
2024-06-18 11:02:40,326 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\wandb-metadata.json
2024-06-18 11:02:40,592 DEBUG   SenderThread:20712 [sender.py:send():379] send: telemetry
2024-06-18 11:02:41,086 INFO    wandb-upload_0:20712 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp0m_duyybwandb\fj1r3hgf-wandb-metadata.json
2024-06-18 11:02:41,595 INFO    wandb-upload_2:20712 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp0m_duyybwandb\g9mx4bjm-diff.patch
2024-06-18 11:02:41,768 INFO    wandb-upload_1:20712 [upload_job.py:push():131] Uploaded file C:\Users\ly\AppData\Local\Temp\tmp0m_duyybwandb\wq6qe9mt-code/system/main.py
2024-06-18 11:02:42,604 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:02:44,356 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\output.log
2024-06-18 11:02:46,382 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\output.log
2024-06-18 11:02:48,251 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:02:48,768 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: pause
2024-06-18 11:02:48,768 INFO    HandlerThread:20712 [handler.py:handle_request_pause():728] stopping system metrics thread or process
2024-06-18 11:02:48,768 INFO    HandlerThread:20712 [system_monitor.py:finish():190] Stopping system monitor
2024-06-18 11:02:48,768 DEBUG   SystemMonitor:20712 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2024-06-18 11:02:48,775 DEBUG   SystemMonitor:20712 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2024-06-18 11:02:48,775 INFO    HandlerThread:20712 [interfaces.py:finish():202] Joined cpu monitor
2024-06-18 11:02:48,775 DEBUG   SystemMonitor:20712 [system_monitor.py:_start():170] Publishing last batch of metrics
2024-06-18 11:02:48,775 INFO    HandlerThread:20712 [interfaces.py:finish():202] Joined disk monitor
2024-06-18 11:02:48,830 INFO    HandlerThread:20712 [interfaces.py:finish():202] Joined gpu monitor
2024-06-18 11:02:48,830 INFO    HandlerThread:20712 [interfaces.py:finish():202] Joined memory monitor
2024-06-18 11:02:48,830 INFO    HandlerThread:20712 [interfaces.py:finish():202] Joined network monitor
2024-06-18 11:02:48,831 DEBUG   SenderThread:20712 [sender.py:send():379] send: stats
2024-06-18 11:02:53,866 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:02:54,924 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:02:54,924 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:02:59,220 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:04,267 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:09,298 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:09,596 INFO    Thread-16 :20712 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Research-Projects-jupyter\PFLlib\system\wandb\run-20240618_110237-mq1q3hm3\files\config.yaml
2024-06-18 11:03:09,940 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:03:09,941 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:03:15,219 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:20,261 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:24,954 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:03:24,954 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:03:26,251 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:31,290 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:36,340 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:39,952 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:03:39,952 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:03:42,228 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:47,283 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:52,312 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: status_report
2024-06-18 11:03:54,964 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: stop_status
2024-06-18 11:03:54,965 DEBUG   SenderThread:20712 [sender.py:send_request():406] send_request: stop_status
2024-06-18 11:03:57,609 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:03:58,875 INFO    SenderThread:20712 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 497, in send
    chunked=chunked,
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\connectionpool.py", line 848, in urlopen
    method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Reseach Software\envs\fl\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\internal\internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\wandb\sdk\lib\gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Reseach Software\envs\fl\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)'))))
2024-06-18 11:03:59,865 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:04:00,004 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:04,389 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:04:05,060 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:10,112 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:12,738 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:04:15,155 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:20,194 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:25,226 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:29,474 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:04:30,252 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:35,298 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:40,345 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:45,387 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:50,419 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:04:55,460 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:00,500 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:02,676 WARNING FileStreamThread:20712 [file_stream.py:request_with_retry():671] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/paddeyzhang/SCL_test/mq1q3hm3/file_stream (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLError(1, '[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)')))). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x000001E6BE453848>>, timeout=60.0), args: ('https://api.wandb.ai/files/paddeyzhang/SCL_test/mq1q3hm3/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2024-06-18 11:05:05,535 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:10,593 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:15,623 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:20,658 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:25,708 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:30,755 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
2024-06-18 11:05:35,804 DEBUG   HandlerThread:20712 [handler.py:handle_request():144] handle_request: keepalive
